// <auto-generated />
using System;
using Eatah.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eatah.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EatahDbContext))]
    [Migration("20260422202355_AddPoultryCategoryAndUpdateLivsmedelsverket")]
    partial class AddPoultryCategoryAndUpdateLivsmedelsverket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eatah.Domain.Entities.DayPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_id");

                    b.Property<Guid>("weekly_plan_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("weekly_plan_id");

                    b.ToTable("day_plans", (string)null);
                });

            modelBuilder.Entity("Eatah.Domain.Entities.DietProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("diet_profiles", (string)null);
                });

            modelBuilder.Entity("Eatah.Domain.Entities.DietRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("MaxPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_week");

                    b.Property<int>("MinPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("min_per_week");

                    b.Property<Guid>("diet_profile_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("diet_profile_id");

                    b.ToTable("diet_rules", (string)null);
                });

            modelBuilder.Entity("Eatah.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("meal_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("meal_id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Eatah.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<int?>("CookingTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cooking_time_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("Eatah.Domain.Entities.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Year", "WeekNumber")
                        .IsUnique();

                    b.ToTable("weekly_plans", (string)null);
                });

            modelBuilder.Entity("Eatah.Domain.Entities.DayPlan", b =>
                {
                    b.HasOne("Eatah.Domain.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eatah.Domain.Entities.WeeklyPlan", null)
                        .WithMany("Days")
                        .HasForeignKey("weekly_plan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Eatah.Domain.Entities.DietRule", b =>
                {
                    b.HasOne("Eatah.Domain.Entities.DietProfile", null)
                        .WithMany("Rules")
                        .HasForeignKey("diet_profile_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eatah.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("Eatah.Domain.Entities.Meal", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("meal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eatah.Domain.Entities.DietProfile", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Eatah.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Eatah.Domain.Entities.WeeklyPlan", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
